### ISSUE TITLE
I have a bunch of floor lamps with RBGIC - I can turn them on and off - but is there a way to change scenes or at least adjust the dimming?

### ISSUE THREAD

**Issue by gleep52** [ivarho/hubitatappndevice#1]
The model is listed as this:

"Corner Floor Lamp DFQY-CS14"

The bar code says:

"X00381JJ0L RGBIC LED Floor Lamp, Gevcc ...,Bedroom,Gaming Room(Black)"

Searching on Amazon I found this link that looks correct: [https://smile.amazon.com/Gevcc-Changing-Corner-Google-Assistant/dp/B09Y1NSVNQ 9](https://smile.amazon.com/Gevcc-Changing-Corner-Google-Assistant/dp/B09Y1NSVNQ)

When I poll the devices I get the DPS values of:
` DPS: {'20': True, '26': 0}`

Is there a way to see or get more functionality from these lights?  I realize programming RGBIC is probably not ideal since it can easily be done and saved as a scene in the Tuya app - but can this driver be adjusted to allow scene changes or dimming possibly?

**Comment by gleep52** [comment]
I've gotten some help from the guys who work on TinyTuya and we've found that these floor lamps use DPS value 51 for the scene payload.  The payloads are in base64 encryption and I can use python to send a new payload and make my lamps use the scenes I have saved, or random weird stuff.  Is there a way to get this functionality into hubitat?  I don't see a way to control DPS 51 and enter a value or create a button to trigger that "scene" to happen.... 

Any help is appreciated.

**Comment by ivarho** [comment]
Issue has been addressed in the newly added RGBW driver.

**Comment by gleep52** [comment]
Hi ivarho -I appreciate the new driver with more fields and functionality - but passing a custom string isn't available and doesn't address my specific "issue" here on github.  My lamps are floorlamps using ICRGB led strips inside (guessing).  So for my app, when I program the LED strip to shuffle colors for specific LEDs, it gives me a saved string value like "AcwLZGRwAAAOAABkATdkAR9kARBkAPFkAMpkANtkAQlk".  My custom payload with node-red is currently set to this code, in order to trigger my lamp to use this "scene" or string from the app.
```
msg.payload = {
    //dps : 1,
    dps: 51,
    set: 'AcwLZGRwAAAOAABkATdkAR9kARBkAPFkAMpkANtkAQlk'
}

/*

    */
return msg;
```

This uses the dps value of 51 which still is not present in your driver (at least from what I can make out).  I know Tuya lamps are all over the map in terms of non-conformity or being uniform in commands/ports/versions/etc.

I was curious if you could make a custom field in your driver that we (end user) can specify the dps value (in my case 51) and have a field to input a string value or values to choose from.  Then have the message payload send those specific values which would trigger my lamps "scene" or string I posted above.  Is that easy and possible?

**Comment by ivarho** [comment]
Feature added in the latest driver update. See function `SendCustomDataToDevice`(endpoint, data)
